lspver=3.17
vscver=1.75.1


curdir=$PWD
owndir=prereq
if [ $0 != "$owndir/fetch.sh" ]
then
    echo "$0: run from repo root, not from $curdir"
    exit 1
fi


echo "{
    \"_doc\": \"set the target versions in fetch.sh, not here: this here is autogenerated from there\",
    \"LSP\": {\"Version\": \"$lspver\", \"File\": \"$owndir/lsp_$lspver.json\"},
    \"VSX\": {\"Version\": \"$vscver\", \"File\": \"$owndir/vsc_$vscver.d.ts\"}
}" > $owndir/meta.json


# fetch LSP stuff

wget -O $owndir/lsp_$lspver.json https://github.com/microsoft/language-server-protocol/raw/gh-pages/_specifications/lsp/$lspver/metaModel/metaModel.json
wget -O $owndir/lsp_$lspver.schema.json https://github.com/microsoft/language-server-protocol/raw/gh-pages/_specifications/lsp/$lspver/metaModel/metaModel.schema.json


# fetch VSCodium stuff

wget -O $owndir/vsc_$vscver.d.ts https://github.com/microsoft/vscode/raw/$vscver/src/vscode-dts/vscode.d.ts
