lspver=3.17
vscver=1.75.1


curdir=$PWD
owndir=prereq
if [ $0 != "$owndir/fetch.sh" ]
then
    echo "$0: run from repo root, not from $curdir"
    exit 1
fi

echo "{
    \"_doc\": \"set the target versions in fetch.sh, not here: this here is autogenerated from there\",
    \"LSP\": {\"Version\": \"$lspver\", \"File\": \"$owndir/lsp_$lspver.json\"},
    \"VSX\": {\"Version\": \"$vscver\", \"File\": \"$owndir/vsc_$vscver.d.ts\"}
}" > $owndir/ver.json

# make tmp dir for repo clones

tmpdir=/tmp/glot-prereq
rm -rf $tmpdir
mkdir $tmpdir



# LSP stuff: fetch metaModel.json

git clone https://github.com/microsoft/language-server-protocol.git --single-branch $tmpdir/repo_lsp

rm -f $owndir/lsp_*.json
cp $tmpdir/repo_lsp/_specifications/lsp/$lspver/metaModel/metaModel.json $owndir/lsp_$lspver.json



# VSCodium stuff: fetch vscode.d.ts

git clone https://github.com/microsoft/vscode.git --single-branch  $tmpdir/repo_vsc
cd $tmpdir/repo_vsc
git pull --tags
git reset --hard $vscver
cd $curdir

rm -f $owndir/vsc_*.d.ts
cp $tmpdir/repo_vsc/src/vscode-dts/vscode.d.ts $owndir/vsc_$vscver.d.ts



# cleanup
rm -rf $tmpdir
